image: ""
secretName: "sms-alerts"
registrySecretName: ""
appName: "sms-alerts-pubsub"
namespace: "sms"
ingressRouteMatch: "Host(`sms.example.local`)"
ingressEntryPointName: "sms-alerts"
ingressEntryPointPort: "80"
defaultPhoneNumber: "123456789"
